language: objective-c
osx_image: xcode10.0

branches:
only:
- develop
- master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- rvm install ruby-2.2.2
- gem install cocoapods
- gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -workspace "MDLIVE New Dashboard.xcworkspace" -scheme "MDLIVE New Dashboard" -sdk iphoneos ONLY_ACTIVE_ARCH=NO | xcpretty -c

